# Generated by Django 4.2.26 on 2025-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                ("opis_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.IntegerField()),
                (
                    "retail_price",
                    models.DecimalField(db_index=True, decimal_places=3, max_digits=6),
                ),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "fuel_station",
                "ordering": ["retail_price"],
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="fuel_statio_state_634fcf_idx"
                    ),
                    models.Index(
                        fields=["retail_price"], name="fuel_statio_retail__081273_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="fuel_statio_latitud_570b61_idx",
                    ),
                    models.Index(
                        fields=["state", "retail_price"],
                        name="fuel_statio_state_abeafd_idx",
                    ),
                ],
            },
        ),
    ]
