# Generated by Django 4.2.26 on 2025-11-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Polypine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encoded", models.TextField()),
            ],
        ),
    ]
